name: SQS Delete Message
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
        - development
        - staging
        - production
        default: 'staging'
      sqs_url:
        description: 'SQS Queue URL'
        required: true
        default: ''
      message_id:
        description: 'SQS Message ID'
        required: true
        default: ''
      
jobs:

  set-env:
    name: Set environment variables
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2

  staging:
    if: "${{ github.event.inputs.environment == 'staging' }}"
    name: Staging
    needs: [set-env]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: login-aws
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Running sqs-delete-message.sh
        run: |
          chmod +x ./sqs-delete-message.sh
          ./sqs-delete-message.sh
        working-directory: ./build
        env:
          URL: '${{ github.event.inputs.sqs_url }}'
          ENVIRONMENT: '${{ github.event.inputs.environment }}'
          ID: '${{ github.event.inputs.message_id }}'
